---
- hosts: balancer
  become: true
  gather_facts: no
  vars:
    server_name: "0.0.0.0"
    document_root: /var/www
  roles:
    - balancer
  
  tasks:
    - name: update packadges
      apt:
        name: nginx
        state: "latest"
        update_cache: yes
    
    - name: Copy files
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve
      tags:
        - continue
  
- hosts: server
  become: true
  gather_facts: no
  vars:
    server_name: "0.0.0.0"
    document_root: /var/www
  roles:
  - server   
  
  tasks:
    - name: update packadges
      apt:
        name: nginx
        state: "latest"
        update_cache: yes

    - name: Copy files
      copy:
        src: "{{ app_root }}"
        dest: "{{ document_root }}"
        mode: preserve
      tags:
        - continue  
  