---
- name: Set config
  copy:
    src: "{{ nginx_conf }}"
    dest: /etc/nginx/sites-available/default
    mode: preserve
    tags:
      - continue

- name: New site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
    notify: Restart
    tags:
      - continue2